-- =========================================================
-- 1. 회원 테이블
-- =========================================================

CREATE TABLE member (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    nickname VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

COMMENT ON TABLE member IS '회원 정보를 관리하는 테이블';

COMMENT ON COLUMN member.member_id IS '회원 고유 식별자';
COMMENT ON COLUMN member.email IS '회원 이메일 주소';
COMMENT ON COLUMN member.nickname IS '회원 닉네임';
COMMENT ON COLUMN member.created_at IS '회원 가입 일시';
COMMENT ON COLUMN member.updated_at IS '회원 정보 최종 수정 일시';
COMMENT ON COLUMN member.deleted_at IS '회원 탈퇴 일시';

-- =========================================================
-- 2. 도서 테이블
-- =========================================================

CREATE TABLE book (
    book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(20) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(100) NOT NULL,
    publisher VARCHAR(100) NOT NULL,
    pub_date DATE NOT NULL,
    price INTEGER NOT NULL CHECK (price >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE book IS '도서 정보를 관리하는 테이블';

COMMENT ON COLUMN book.book_id IS '도서 고유 식별자';
COMMENT ON COLUMN book.isbn IS '국제표준도서번호';
COMMENT ON COLUMN book.title IS '도서 제목';
COMMENT ON COLUMN book.author IS '도서 저자';
COMMENT ON COLUMN book.publisher IS '도서 출판사';
COMMENT ON COLUMN book.pub_date IS '도서 출판일';
COMMENT ON COLUMN book.price IS '도서 가격';
COMMENT ON COLUMN book.created_at IS '도서 정보 등록 일시';
COMMENT ON COLUMN book.updated_at IS '도서 정보 최종 수정 일시';

-- =========================================================
-- 3. 카테고리 테이블
-- =========================================================

CREATE TABLE category (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE category IS '도서 카테고리 정보를 관리하는 테이블';

COMMENT ON COLUMN category.category_id IS '카테고리 고유 식별자';
COMMENT ON COLUMN category.name IS '카테고리 이름';
COMMENT ON COLUMN category.created_at IS '카테고리 생성 일시';
COMMENT ON COLUMN category.updated_at IS '카테고리 정보 최종 수정 일시';

-- =========================================================
-- 4. 도서 대여 테이블
-- =========================================================

CREATE TABLE rental (
    rental_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'RENTED',
    rental_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_at TIMESTAMP NOT NULL,
    returned_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_rental_member
        FOREIGN KEY (member_id) REFERENCES member(member_id),

    CONSTRAINT fk_rental_book
        FOREIGN KEY (book_id) REFERENCES book(book_id),

    CONSTRAINT chk_rental_status
        CHECK (status IN ('RENTED', 'OVERDUE', 'RETURNED')),

    CONSTRAINT chk_rental_due_at
        CHECK (due_at >= rental_at),

    CONSTRAINT chk_rental_returned_at
        CHECK (returned_at IS NULL OR returned_at >= rental_at)
);

COMMENT ON TABLE rental IS '도서 대여 및 반납 기록을 관리하는 테이블';

COMMENT ON COLUMN rental.rental_id IS '도서 대여 기록 고유 식별자';
COMMENT ON COLUMN rental.member_id IS '도서를 대여한 회원 식별자';
COMMENT ON COLUMN rental.book_id IS '대여한 도서 식별자';
COMMENT ON COLUMN rental.status IS '도서 대여 상태 (RENTED, OVERDUE, RETURNED)';
COMMENT ON COLUMN rental.rental_at IS '도서 대여 일시';
COMMENT ON COLUMN rental.due_at IS '도서 반납 예정 일시';
COMMENT ON COLUMN rental.returned_at IS '도서 실제 반납 일시';
COMMENT ON COLUMN rental.created_at IS '도서 대여 기록 생성 일시';
COMMENT ON COLUMN rental.updated_at IS '도서 대여 기록 최종 수정 일시';