-- =========================================================
-- 1. 회원 테이블
-- =========================================================

CREATE TABLE member (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    nickname VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

COMMENT ON TABLE member IS '회원 정보를 관리하는 테이블';

COMMENT ON COLUMN member.member_id IS '회원 고유 식별자';
COMMENT ON COLUMN member.email IS '회원 이메일 주소';
COMMENT ON COLUMN member.nickname IS '회원 닉네임';
COMMENT ON COLUMN member.created_at IS '회원 가입 일시';
COMMENT ON COLUMN member.updated_at IS '회원 정보 최종 수정 일시';
COMMENT ON COLUMN member.deleted_at IS '회원 탈퇴 일시';

-- =========================================================
-- 2. 도서 테이블
-- =========================================================

CREATE TABLE book (
    book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(20) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(100) NOT NULL,
    publisher VARCHAR(100) NOT NULL,
    pub_date DATE NOT NULL,
    price INTEGER NOT NULL CHECK (price >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE book IS '도서 정보를 관리하는 테이블';

COMMENT ON COLUMN book.book_id IS '도서 고유 식별자';
COMMENT ON COLUMN book.isbn IS '국제표준도서번호';
COMMENT ON COLUMN book.title IS '도서 제목';
COMMENT ON COLUMN book.author IS '도서 저자';
COMMENT ON COLUMN book.publisher IS '도서 출판사';
COMMENT ON COLUMN book.pub_date IS '도서 출판일';
COMMENT ON COLUMN book.price IS '도서 가격';
COMMENT ON COLUMN book.created_at IS '도서 정보 등록 일시';
COMMENT ON COLUMN book.updated_at IS '도서 정보 최종 수정 일시';