-- =========================================================
-- 1. 회원 테이블
-- =========================================================

CREATE TABLE member (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    nickname VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

COMMENT ON TABLE member IS '회원 정보를 관리하는 테이블';

COMMENT ON COLUMN member.member_id IS '회원 고유 식별자';
COMMENT ON COLUMN member.email IS '회원 이메일 주소';
COMMENT ON COLUMN member.nickname IS '회원 닉네임';
COMMENT ON COLUMN member.created_at IS '회원 가입 일시';
COMMENT ON COLUMN member.updated_at IS '회원 정보 최종 수정 일시';
COMMENT ON COLUMN member.deleted_at IS '회원 탈퇴 일시';